#ci.gocd.yaml
format_version: 9
pipelines:
  cube: # definition of mypipe1 pipeline
    group: Personal # note that the group name can contain only of alphanumeric & underscore characters
    template: go-test-only
    materials:
      cube: # this is the name of material, the name can contain only of alphanumeric & underscore characters
        # keyword git says about type of material and url at once
        scm: scm-fb-cube