#ci.gocd.yaml
format_version: 9
pipelines:
  cube: # definition of mypipe1 pipeline
    group: MSK998 # note that the group name can contain only of alphanumeric & underscore characters
    materials:
      cube: # this is the name of material, the name can contain only of alphanumeric & underscore characters
        # keyword git says about type of material and url at once
        git: https://github.com/MSK998/cube.git
    stages: # list of stages in order
      - test: # name of stage
          clean_workspace: true
          jobs:
            test: # name of the job
              resources:
               - go
              tasks: # ordered list of tasks to execute in job csharp
               - exec: # indicates type of task
                   command: go
                   arguments:
                    - test
                    - ./...